version 0.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -525,12 +525,14 @@ fi
 if test -z "${PVM_ROOT}"; then
     echo "Warning: PVM_ROOT not defined."
     echo "Try to guess where pvm is installed..."
-    if test -d /usr/lib/pvm3; then
+    if test -d /usr/lib/pvm3; then                      # Debian
         PVM_ROOT=/usr/lib/pvm3
-    elif test -d ${HOME}/pvm3; then
+    elif test -d /usr/share/pvm3; then                  # Red Hat
+        PVM_ROOT=/usr/share/pvm3
+    elif test -d ${HOME}/pvm3; then                     # User installed
         PVM_ROOT=${HOME}/pvm3
     fi
-    if test -n ${PVM_ROOT}; then
+    if test -n "${PVM_ROOT}"; then
         echo "Found pvm: ${PVM_ROOT} "
         echo "Warning: You need set PVM_ROOT to ${PVM_ROOT} before use pvm."
         echo "See pvm_intro(1PVM)"
@@ -551,7 +553,7 @@ fi
 echo "PVM_ARCH is ${PVM_ARCH}"
 
 echo $ac_n "checking how to run the C preprocessor""... $ac_c" 1>&6
-echo "configure:555: checking how to run the C preprocessor" >&5
+echo "configure:557: checking how to run the C preprocessor" >&5
 # On Suns, sometimes $CPP names a directory.
 if test -n "$CPP" && test -d "$CPP"; then
   CPP=
@@ -566,13 +568,13 @@ else
   # On the NeXT, cc -E runs the code through the compiler's parser,
   # not just through cpp.
   cat > conftest.$ac_ext <<EOF
-#line 570 "configure"
+#line 572 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:576: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:578: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -583,13 +585,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -E -traditional-cpp"
   cat > conftest.$ac_ext <<EOF
-#line 587 "configure"
+#line 589 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:593: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:595: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -600,13 +602,13 @@ else
   rm -rf conftest*
   CPP="${CC-cc} -nologo -E"
   cat > conftest.$ac_ext <<EOF
-#line 604 "configure"
+#line 606 "configure"
 #include "confdefs.h"
 #include <assert.h>
 Syntax Error
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:610: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:612: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   :
@@ -632,17 +634,17 @@ echo "$ac_t""$CPP" 1>&6
 
 ac_safe=`echo "pvm3.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for pvm3.h""... $ac_c" 1>&6
-echo "configure:636: checking for pvm3.h" >&5
+echo "configure:638: checking for pvm3.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 641 "configure"
+#line 643 "configure"
 #include "confdefs.h"
 #include <pvm3.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:646: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:648: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -661,9 +663,13 @@ if eval "test \"`echo '$ac_cv_header_'$ac_safe`\" = yes"; then
   PVM_INCLUDE=""
 else
   echo "$ac_t""no" 1>&6
-echo "Try to find pvm3.h in ${PVM_ROOT}/include ..."
-    if test -f ${PVM_ROOT}/include/pvm3.h; then
-        echo "Found"
+
+    echo "Try to find pvm3.h ..."
+    if test -f /usr/local/include/pvm3.h; then
+        echo "Found in /usr/local/include"
+        PVM_INCLUDE="-I/usr/local/include"
+    elif test -f ${PVM_ROOT}/include/pvm3.h; then
+        echo "Found in ${PVM_ROOT}/include"
         PVM_INCLUDE="-I${PVM_ROOT}/include"
     else 
         echo "Cannot find pvm header file."; exit 1
@@ -671,8 +677,9 @@ echo "Try to find pvm3.h in ${PVM_ROOT}/include ..."
 
 fi
 
+
 echo $ac_n "checking for pvm_mytid in -lpvm3""... $ac_c" 1>&6
-echo "configure:676: checking for pvm_mytid in -lpvm3" >&5
+echo "configure:683: checking for pvm_mytid in -lpvm3" >&5
 ac_lib_var=`echo pvm3'_'pvm_mytid | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -680,7 +687,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpvm3  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 684 "configure"
+#line 691 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -691,7 +698,7 @@ int main() {
 pvm_mytid()
 ; return 0; }
 EOF
-if { (eval echo configure:695: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:702: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -709,9 +716,13 @@ if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
   PVM_LIBS=""
 else
   echo "$ac_t""no" 1>&6
-echo "Try to find libpvm3 in ${PVM_ROOT}/lib/${PVM_ARCH} ..."
-    if test -f ${PVM_ROOT}/lib/${PVM_ARCH}/libpvm3.a; then
-        echo "Found"
+
+    echo "Try to find libpvm3 ..."
+    if test -f /usr/local/lib/libpvm3.a; then
+        echo "Found in /usr/local/lib"
+        PVM_LIBS="-L/usr/local/lib"
+    elif test -f ${PVM_ROOT}/lib/${PVM_ARCH}/libpvm3.a; then
+        echo "Found in ${PVM_ROOT}/lib/${PVM_ARCH}"
         PVM_LIBS="-L${PVM_ROOT}/lib/${PVM_ARCH}"
     else
         echo "Cannot find libpvm3"; exit 1
@@ -720,8 +731,98 @@ echo "Try to find libpvm3 in ${PVM_ROOT}/lib/${PVM_ARCH} ..."
 fi
 
 
-PKG_LIBS="${PVM_LIBS} -lpvm3"
+# Extract the first word of "pvmd", so it can be a program name with args.
+set dummy pvmd; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:738: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_PVMD'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$PVMD" in
+  /*)
+  ac_cv_path_PVMD="$PVMD" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_PVMD="$PVMD" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_PVMD="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_PVMD" && ac_cv_path_PVMD="
+    echo "Cannot find pvmd executable"
+    echo "Include it in your path or check your pvm installation."
+    exit 1
+"
+  ;;
+esac
+fi
+PVMD="$ac_cv_path_PVMD"
+if test -n "$PVMD"; then
+  echo "$ac_t""$PVMD" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+# Extract the first word of "pvmgs", so it can be a program name with args.
+set dummy pvmgs; ac_word=$2
+echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
+echo "configure:779: checking for $ac_word" >&5
+if eval "test \"`echo '$''{'ac_cv_path_PVMGSPATH'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  case "$PVMGSPATH" in
+  /*)
+  ac_cv_path_PVMGSPATH="$PVMGSPATH" # Let the user override the test with a path.
+  ;;
+  ?:/*)			 
+  ac_cv_path_PVMGSPATH="$PVMGSPATH" # Let the user override the test with a dos path.
+  ;;
+  *)
+  IFS="${IFS= 	}"; ac_save_ifs="$IFS"; IFS=":"
+  ac_dummy="$PATH"
+  for ac_dir in $ac_dummy; do 
+    test -z "$ac_dir" && ac_dir=.
+    if test -f $ac_dir/$ac_word; then
+      ac_cv_path_PVMGSPATH="$ac_dir/$ac_word"
+      break
+    fi
+  done
+  IFS="$ac_save_ifs"
+  test -z "$ac_cv_path_PVMGSPATH" && ac_cv_path_PVMGSPATH="
+    if test -f ${PVM_ROOT}/bin/${PVM_ARCH}/pvmgs; then
+        PVMGSPATH=${PVM_ROOT}/bin/${PVM_ARCH}
+        echo "Found in ${PVM_ROOT}/bin/${PVM_ARCH}"
+    else 
+        echo "Cannot find pvmgs executable"
+        echo "Include it in your path or check your pvm installation."
+        exit 1
+    fi
+"
+  ;;
+esac
+fi
+PVMGSPATH="$ac_cv_path_PVMGSPATH"
+if test -n "$PVMGSPATH"; then
+  echo "$ac_t""$PVMGSPATH" 1>&6
+else
+  echo "$ac_t""no" 1>&6
+fi
+
+
+PKG_LIBS="${PVM_LIBS} -lpvm3 -lgpvm3"
 PKG_CPPFLAGS="${PVM_INCLUDE}"
+PVMGSPATH=`dirname $PVMGSPATH`
+# PVMGSPATH=${PVMGSPATH%/*}
+
 
 
 
@@ -840,7 +941,7 @@ done
 
 ac_given_srcdir=$srcdir
 
-trap 'rm -fr `echo "src/Makevars" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
+trap 'rm -fr `echo "src/Makevars inst/pvmhosts" | sed "s/:[^ ]*//g"` conftest*; exit 1' 1 2 15
 EOF
 cat >> $CONFIG_STATUS <<EOF
 
@@ -873,6 +974,8 @@ s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
 s%@CPP@%$CPP%g
+s%@PVMD@%$PVMD%g
+s%@PVMGSPATH@%$PVMGSPATH%g
 s%@PVM_ROOT@%$PVM_ROOT%g
 s%@PVM_ARCH@%$PVM_ARCH%g
 s%@PKG_LIBS@%$PKG_LIBS%g
@@ -918,7 +1021,7 @@ EOF
 
 cat >> $CONFIG_STATUS <<EOF
 
-CONFIG_FILES=\${CONFIG_FILES-"src/Makevars"}
+CONFIG_FILES=\${CONFIG_FILES-"src/Makevars inst/pvmhosts"}
 EOF
 cat >> $CONFIG_STATUS <<\EOF
 for ac_file in .. $CONFIG_FILES; do if test "x$ac_file" != x..; then
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1,14 +1,18 @@
+# Process this file with autoconf to produce a configure script.
+
 AC_INIT(DESCRIPTION)
 
 if test -z "${PVM_ROOT}"; then
     echo "Warning: PVM_ROOT not defined."
     echo "Try to guess where pvm is installed..."
-    if test -d /usr/lib/pvm3; then
+    if test -d /usr/lib/pvm3; then                      # Debian
         PVM_ROOT=/usr/lib/pvm3
-    elif test -d ${HOME}/pvm3; then
+    elif test -d /usr/share/pvm3; then                  # Red Hat
+        PVM_ROOT=/usr/share/pvm3
+    elif test -d ${HOME}/pvm3; then                     # User installed
         PVM_ROOT=${HOME}/pvm3
     fi
-    if test -n ${PVM_ROOT}; then
+    if test -n "${PVM_ROOT}"; then
         echo "Found pvm: ${PVM_ROOT} "
         echo "Warning: You need set PVM_ROOT to ${PVM_ROOT} before use pvm."
         echo "See pvm_intro(1PVM)"
@@ -28,31 +32,58 @@ fi
 
 echo "PVM_ARCH is ${PVM_ARCH}"
 
-AC_CHECK_HEADER(pvm3.h,PVM_INCLUDE="",
-    echo "Try to find pvm3.h in ${PVM_ROOT}/include ..."
-    if test -f ${PVM_ROOT}/include/pvm3.h; then
-        echo "Found"
+AC_CHECK_HEADER(pvm3.h,PVM_INCLUDE="",[
+    echo "Try to find pvm3.h ..."
+    if test -f /usr/local/include/pvm3.h; then
+        echo "Found in /usr/local/include"
+        PVM_INCLUDE="-I/usr/local/include"
+    elif test -f ${PVM_ROOT}/include/pvm3.h; then
+        echo "Found in ${PVM_ROOT}/include"
         PVM_INCLUDE="-I${PVM_ROOT}/include"
     else 
         echo "Cannot find pvm header file."; exit 1
     fi
-)
-AC_CHECK_LIB(pvm3,pvm_mytid,PVM_LIBS="",
-    echo "Try to find libpvm3 in ${PVM_ROOT}/lib/${PVM_ARCH} ..."
-    if test -f ${PVM_ROOT}/lib/${PVM_ARCH}/libpvm3.a; then
-        echo "Found"
+])
+
+AC_CHECK_LIB(pvm3,pvm_mytid,PVM_LIBS="",[
+    echo "Try to find libpvm3 ..."
+    if test -f /usr/local/lib/libpvm3.a; then
+        echo "Found in /usr/local/lib"
+        PVM_LIBS="-L/usr/local/lib"
+    elif test -f ${PVM_ROOT}/lib/${PVM_ARCH}/libpvm3.a; then
+        echo "Found in ${PVM_ROOT}/lib/${PVM_ARCH}"
         PVM_LIBS="-L${PVM_ROOT}/lib/${PVM_ARCH}"
     else
         echo "Cannot find libpvm3"; exit 1
     fi
-)
+])
 
-PKG_LIBS="${PVM_LIBS} -lpvm3"
+AC_PATH_PROG(PVMD,pvmd,[
+    echo "Cannot find pvmd executable"
+    echo "Include it in your path or check your pvm installation."
+    exit 1
+])
+
+AC_PATH_PROG(PVMGSPATH,pvmgs,[
+    if test -f ${PVM_ROOT}/bin/${PVM_ARCH}/pvmgs; then
+        PVMGSPATH=${PVM_ROOT}/bin/${PVM_ARCH}
+        echo "Found in ${PVM_ROOT}/bin/${PVM_ARCH}"
+    else 
+        echo "Cannot find pvmgs executable"
+        echo "Include it in your path or check your pvm installation."
+        exit 1
+    fi
+])
+
+PKG_LIBS="${PVM_LIBS} -lpvm3 -lgpvm3"
 PKG_CPPFLAGS="${PVM_INCLUDE}"
+PVMGSPATH=`dirname $PVMGSPATH`
+# PVMGSPATH=${PVMGSPATH%/*}
 
 AC_SUBST(PVM_ROOT)
 AC_SUBST(PVM_ARCH)
 AC_SUBST(PKG_LIBS)
 AC_SUBST(PKG_CPPFLAGS)
+AC_SUBST(PVMGSPATH)
 
-AC_OUTPUT(src/Makevars)
+AC_OUTPUT(src/Makevars inst/pvmhosts)
